### PR TITLE
Fixes for mailbox auditing

### PR DESCRIPTION
**Pull request by 007**
* Optimize `Import-PSSession`
* Don't fail on "bad" mailbox values
* Stop trying to use pseudo-deprecated output filter

### CODE REVIEW

**Comment by 007** [comment]
@o365devx @bkoeller bump so this doesn't languish for 5 quarters like previous PRs

**Comment by 007** [comment]
Another month, another bump!

**Comment by PsychoData** [comment]
've about given  n these actually gettinig reviewed and merged.
You would think that f they didn't want things submitted they would change
it so you couldn't submit and then sign the CLA

There are loads of people who have submitted commits to fix the dang
RedirectsTo to RedirectTo like it should be so it ACTUALLY works
been sitting for over a year or longer

**Comment by 007** [comment]
Another month, another bump redux.

Adding @davidchesnut as the only other minor contributor / $MSFT org member that might have context and might care to take action here.

**Comment by arjancornelissen** [comment]
I wouldn't do line 23, removing the out-gridview.
Checking large sets of mailboxes will not work in the normal output.
Get-mailbox should be placed in a variable and have a select-object DistinguishedName

**Comment by 007** [comment]
`Out-GridView` [doesn't exist in PS6](https://powershell.org/forums/topic/powershell-core-6-1-does-not-recognize-out-gridview/#post-138564) so it makes sense to remove that until it comes back in a later dot-revision or in v7. The commit message doesn't explain as it should have, that's why I included `pseudo-deprecated output filter` in the pull description.

You should submit a PR to address the second half of your comment if that's a more standard / accepted convention, this was my first encounter with PowerShell so my code is definitely less than ideal.

**Pull request merged**
